from vector import Vector
from pygame.locals import *
FPS = 60
BASE_SCORE = 50
SNAKE_SPEED = 6
SNAKE_INC_SPEED = .25
SNAKE_INIT_LENGTH = 3
COLOR_BG = (45, 45, 45)
COLOR_SNAKE_OUT = (0, 155, 0)
COLOR_SNAKE_IN = (0, 255, 0)
COLOR_APPLE = (255, 0, 0)
DEATH_COLOR = (155, 0, 0)
TEXT_COLOR = (242, 242, 242)
WHITE = (255, 255, 255)
SCREEN_WIDTH = 800
SCREEN_HEIGHT = 600
BLOCK_SIZE = 25
WORLD_SIZE = BLOCK_SIZE, BLOCK_SIZE
BLOCK_WIDTH = SCREEN_WIDTH // BLOCK_SIZE
BLOCK_HEIGHT = SCREEN_HEIGHT // BLOCK_SIZE
DIRECTION_UP = Vector((0, -1))
DIRECTION_DOWN = Vector((0, 1))
DIRECTION_LEFT = Vector((-1, 0))
DIRECTION_RIGHT = Vector((1, 0))
KEY_DIRECTION = {
    K_w: DIRECTION_UP, K_UP: DIRECTION_UP,
    K_s: DIRECTION_DOWN, K_DOWN: DIRECTION_DOWN,
    K_a: DIRECTION_LEFT, K_LEFT: DIRECTION_LEFT,
    K_d: DIRECTION_RIGHT, K_RIGHT: DIRECTION_RIGHT,
}
GAMEOVER = 0
PLAYING = 1
START_MENU = 2
